from __future__ import annotations

from enum import Enum


class WorkflowRunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    ABORTED = "ABORTED"


class WorkflowRunCompletionReason(str, Enum):
    PARTIAL_FAILURE = "PARTIAL_FAILURE"


class WorkflowProcessStatus(str, Enum):
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    EXITED = "EXITED"
    LOST = "LOST"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    FAILED = "FAILED"


class NodeRunStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    WAITING_DEPENDENCY = "WAITING_DEPENDENCY"
    WAITING_PERMISSION = "WAITING_PERMISSION"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    LONG_RUNNING = "LONG_RUNNING"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    SUSPECTED_HUNG = "SUSPECTED_HUNG"
    TIMED_OUT = "TIMED_OUT"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class TableRole(str, Enum):
    CURRENT = "CURRENT"
    AUXILIARY = "AUXILIARY"
    SHARED = "SHARED"


class TableStorageKind(str, Enum):
    MEMORY = "MEMORY"
    RUNTIME_SQL = "RUNTIME_SQL"


class TableScope(str, Enum):
    WORKFLOW_SCOPE = "WORKFLOW_SCOPE"
    SHARED_SCOPE = "SHARED_SCOPE"


class TableMutability(str, Enum):
    WORKING_MUTABLE = "WORKING_MUTABLE"
    PUBLISHED_IMMUTABLE = "PUBLISHED_IMMUTABLE"


class TableLeaseType(str, Enum):
    READ = "READ"
    WRITE = "WRITE"


class TableLeaseStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"


class LifecycleStatus(str, Enum):
    STAGING = "STAGING"
    PUBLISHED = "PUBLISHED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
    RELEASABLE = "RELEASABLE"
    RELEASED = "RELEASED"
    ORPHANED = "ORPHANED"


class NodeResultStatus(str, Enum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ErrorOrigin(str, Enum):
    ENGINE = "ENGINE"
    WORKFLOW_PROCESS = "WORKFLOW_PROCESS"
    EXECUTOR = "EXECUTOR"
    NODE = "NODE"
    API = "API"
    DATA_PROVIDER = "DATA_PROVIDER"


class IPCMessageType(str, Enum):
    WORKFLOW_PROCESS_READY = "WORKFLOW_PROCESS_READY"
    WORKFLOW_PROCESS_HEARTBEAT = "WORKFLOW_PROCESS_HEARTBEAT"
    WORKFLOW_CANCEL_REQUEST = "WORKFLOW_CANCEL_REQUEST"
    RUNTIME_EVENT = "RUNTIME_EVENT"
    WORKFLOW_PROCESS_COMPLETED = "WORKFLOW_PROCESS_COMPLETED"
    WORKFLOW_PROCESS_FAILED = "WORKFLOW_PROCESS_FAILED"
    EXECUTOR_READY = "EXECUTOR_READY"
    EXECUTOR_HEARTBEAT = "EXECUTOR_HEARTBEAT"
    EXECUTOR_SHUTDOWN_REQUEST = "EXECUTOR_SHUTDOWN_REQUEST"
    NODE_TASK_SUBMIT = "NODE_TASK_SUBMIT"
    NODE_TASK_ACCEPTED = "NODE_TASK_ACCEPTED"
    NODE_TASK_HEARTBEAT = "NODE_TASK_HEARTBEAT"
    NODE_TASK_PROGRESS = "NODE_TASK_PROGRESS"
    NODE_TASK_CANCEL_REQUEST = "NODE_TASK_CANCEL_REQUEST"
    NODE_TASK_COMPLETED = "NODE_TASK_COMPLETED"
    NODE_TASK_FAILED = "NODE_TASK_FAILED"


class EventType(str, Enum):
    ENGINE_READY = "ENGINE_READY"
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_FINISHED = "WORKFLOW_FINISHED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    NODE_QUEUED = "NODE_QUEUED"
    NODE_STARTED = "NODE_STARTED"
    NODE_PROGRESS = "NODE_PROGRESS"
    NODE_LONG_RUNNING = "NODE_LONG_RUNNING"
    NODE_FINISHED = "NODE_FINISHED"
    NODE_FAILED = "NODE_FAILED"
    NODE_TIMEOUT = "NODE_TIMEOUT"
    EXECUTOR_STARTED = "EXECUTOR_STARTED"
    EXECUTOR_EXITED = "EXECUTOR_EXITED"
    EXECUTOR_RESTARTED = "EXECUTOR_RESTARTED"
    DATA_STAGED = "DATA_STAGED"
    DATA_PUBLISHED = "DATA_PUBLISHED"
    DATA_RELEASED = "DATA_RELEASED"
    SHARED_PUBLICATION_AVAILABLE = "SHARED_PUBLICATION_AVAILABLE"
    AUDIT_EVENT_CREATED = "AUDIT_EVENT_CREATED"
