from __future__ import annotations

from flowweaver.node_executor.builtin_fault import (
    DELAY_TEST_NODE_TYPE,
    FAULT_TEST_NODE_TYPE,
)
from flowweaver.nodes.builtin_shared_table import (
    PUBLISH_SHARED_TABLES_NODE_TYPE,
    READ_SHARED_TABLES_NODE_TYPE,
)
from flowweaver.nodes.builtin_sql import SQL_MAPPING_NODE_TYPE
from flowweaver.nodes.builtin_table_node_types import (
    ADD_COLUMNS_NODE_TYPE,
    ADD_CURRENT_DATETIME_COLUMN_NODE_TYPE,
    ADVANCED_FILTER_ROWS_NODE_TYPE,
    BATCH_RENAME_FILES_NODE_TYPE,
    CONDITION_FLAG_NODE_TYPE,
    CONDITIONAL_JUMP_NODE_TYPE,
    COPY_COLUMN_NODE_TYPE,
    COPY_ROWS_NODE_TYPE,
    DEDUPLICATE_ROWS_NODE_TYPE,
    DELETE_COLUMNS_NODE_TYPE,
    DELETE_ROWS_NODE_TYPE,
    EXTRACT_TEXT_NODE_TYPE,
    FILL_CELLS_NODE_TYPE,
    FILL_RANGE_NODE_TYPE,
    FILL_SEQUENCE_NODE_TYPE,
    FILTER_ROWS_NODE_TYPE,
    GENERATE_TEST_TABLE_NODE_TYPE,
    JUMP_ANCHOR_NODE_TYPE,
    LIST_FILES_NODE_TYPE,
    LOOKUP_MATCHED_FIELD_NAME_NODE_TYPE,
    LOOP_JUDGE_NODE_TYPE,
    LOOP_START_NODE_TYPE,
    MERGE_COLUMNS_NODE_TYPE,
    NUMERIC_COLUMN_OPERATION_NODE_TYPE,
    PARSE_DATETIME_NODE_TYPE,
    PLUGIN_NODE_TYPE,
    RENAME_COLUMNS_NODE_TYPE,
    REORDER_COLUMNS_NODE_TYPE,
    REPLACE_TEXT_NODE_TYPE,
    SAVE_MEMORY_TABLE_NODE_TYPE,
    SAVE_RUN_TABLE_NODE_TYPE,
    SUB_WORKFLOW_NODE_TYPE,
    UNCONDITIONAL_JUMP_NODE_TYPE,
    UNPIVOT_ROWS_NODE_TYPE,
    WRITE_BACK_TABLE_NODE_TYPE,
    WRITE_SELECTED_COLUMNS_NODE_TYPE,
)
from flowweaver.nodes.default_node_schemas import (
    _add_columns_schema,
    _add_current_datetime_column_schema,
    _advanced_filter_rows_schema,
    _batch_rename_files_schema,
    _condition_flag_schema,
    _conditional_jump_schema,
    _copy_column_schema,
    _copy_rows_schema,
    _deduplicate_rows_schema,
    _delete_columns_schema,
    _delete_rows_schema,
    _extract_text_schema,
    _fill_cells_schema,
    _fill_range_schema,
    _fill_sequence_schema,
    _filter_rows_schema,
    _generate_test_table_schema,
    _jump_anchor_schema,
    _list_files_schema,
    _lookup_matched_field_name_schema,
    _loop_judge_schema,
    _loop_start_schema,
    _merge_columns_schema,
    _numeric_column_operation_schema,
    _parse_datetime_schema,
    _plugin_node_schema,
    _publish_shared_tables_schema,
    _read_shared_tables_schema,
    _rename_columns_schema,
    _reorder_columns_schema,
    _replace_text_schema,
    _save_memory_table_schema,
    _save_run_table_schema,
    _sql_mapping_schema,
    _subworkflow_schema,
    _unconditional_jump_schema,
    _unpivot_rows_schema,
    _write_back_table_schema,
    _write_selected_columns_schema,
)
from flowweaver.nodes.registry import (
    NodeDefinitionSpec,
    NodePortSpec,
    NodeRegistry,
    NodeTableInputSlotSpec,
    NodeTableOutputSlotSpec,
)
from flowweaver.protocols.enums import TableRole, TableStorageKind

_READABLE_TABLE_STORAGE_KINDS = (
    TableStorageKind.RUNTIME_SQL,
    TableStorageKind.MEMORY,
    TableStorageKind.EXTERNAL_SQL,
)
_NODE_EXECUTION_READABLE_TABLE_STORAGE_KINDS = (
    TableStorageKind.RUNTIME_SQL,
    TableStorageKind.MEMORY,
)


def create_default_node_registry() -> NodeRegistry:
    registry = NodeRegistry()
    for definition in default_node_definitions():
        registry.register(definition)
    return registry


def default_node_definitions() -> tuple[NodeDefinitionSpec, ...]:
    return (
        NodeDefinitionSpec(
            node_type=GENERATE_TEST_TABLE_NODE_TYPE,
            node_version="1.0",
            display_name="Generate Test Table",
            output_ports=(NodePortSpec("out"),),
            output_table_slots=(
                _source_output_table_slot(
                    "out",
                    display_name="Current table",
                    description="Generated table for the main workflow chain.",
                ),
            ),
            config_schema=_generate_test_table_schema(),
        ),
        NodeDefinitionSpec(
            node_type=FILTER_ROWS_NODE_TYPE,
            node_version="1.0",
            display_name="Filter Rows",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_filter_rows_schema(),
        ),
        NodeDefinitionSpec(
            node_type=ADD_COLUMNS_NODE_TYPE,
            node_version="1.0",
            display_name="Add Column",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_add_columns_schema(),
        ),
        NodeDefinitionSpec(
            node_type=DELETE_COLUMNS_NODE_TYPE,
            node_version="1.0",
            display_name="Delete Columns",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_delete_columns_schema(),
        ),
        NodeDefinitionSpec(
            node_type=COPY_COLUMN_NODE_TYPE,
            node_version="1.0",
            display_name="Copy Column",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_copy_column_schema(),
        ),
        NodeDefinitionSpec(
            node_type=REORDER_COLUMNS_NODE_TYPE,
            node_version="1.0",
            display_name="Reorder Columns",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_reorder_columns_schema(),
        ),
        NodeDefinitionSpec(
            node_type=RENAME_COLUMNS_NODE_TYPE,
            node_version="1.0",
            display_name="Rename Columns",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_rename_columns_schema(),
        ),
        NodeDefinitionSpec(
            node_type=FILL_CELLS_NODE_TYPE,
            node_version="1.0",
            display_name="Fill Cells",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_fill_cells_schema(),
        ),
        NodeDefinitionSpec(
            node_type=FILL_RANGE_NODE_TYPE,
            node_version="1.0",
            display_name="Fill Range",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_fill_range_schema(),
        ),
        NodeDefinitionSpec(
            node_type=FILL_SEQUENCE_NODE_TYPE,
            node_version="1.0",
            display_name="Fill Sequence",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_fill_sequence_schema(),
        ),
        NodeDefinitionSpec(
            node_type=REPLACE_TEXT_NODE_TYPE,
            node_version="1.0",
            display_name="Replace Text",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_replace_text_schema(),
        ),
        NodeDefinitionSpec(
            node_type=DELETE_ROWS_NODE_TYPE,
            node_version="1.0",
            display_name="Delete Rows",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_delete_rows_schema(),
        ),
        NodeDefinitionSpec(
            node_type=COPY_ROWS_NODE_TYPE,
            node_version="1.0",
            display_name="Copy Rows",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_copy_rows_schema(),
        ),
        NodeDefinitionSpec(
            node_type=UNPIVOT_ROWS_NODE_TYPE,
            node_version="1.0",
            display_name="Unpivot Rows",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_unpivot_rows_schema(),
        ),
        NodeDefinitionSpec(
            node_type=DEDUPLICATE_ROWS_NODE_TYPE,
            node_version="1.0",
            display_name="Deduplicate Rows",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_deduplicate_rows_schema(),
        ),
        NodeDefinitionSpec(
            node_type=ADVANCED_FILTER_ROWS_NODE_TYPE,
            node_version="1.0",
            display_name="Advanced Filter Rows",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_advanced_filter_rows_schema(),
        ),
        NodeDefinitionSpec(
            node_type=EXTRACT_TEXT_NODE_TYPE,
            node_version="1.0",
            display_name="Extract Text",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_extract_text_schema(),
        ),
        NodeDefinitionSpec(
            node_type=LOOKUP_MATCHED_FIELD_NAME_NODE_TYPE,
            node_version="1.0",
            display_name="Lookup Matched Field Name",
            input_ports=(
                NodePortSpec("in", required=True),
                NodePortSpec("lookup", required=True),
            ),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=(
                _input_table_slot(
                    "in",
                    display_name="Main table",
                    description="Main table to annotate with lookup results.",
                ),
                _input_table_slot(
                    "lookup",
                    display_name="Lookup table",
                    description="Reference table used for field-name lookup.",
                ),
            ),
            output_table_slots=(
                _current_output_table_slot(
                    "out",
                    display_name="Current table",
                    description="Main workflow table after lookup matching.",
                ),
            ),
            config_schema=_lookup_matched_field_name_schema(),
        ),
        NodeDefinitionSpec(
            node_type=MERGE_COLUMNS_NODE_TYPE,
            node_version="1.0",
            display_name="Merge Columns",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_merge_columns_schema(),
        ),
        NodeDefinitionSpec(
            node_type=NUMERIC_COLUMN_OPERATION_NODE_TYPE,
            node_version="1.0",
            display_name="Numeric Column Operation",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_numeric_column_operation_schema(),
        ),
        NodeDefinitionSpec(
            node_type=ADD_CURRENT_DATETIME_COLUMN_NODE_TYPE,
            node_version="1.0",
            display_name="Add Current DateTime Column",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_add_current_datetime_column_schema(),
        ),
        NodeDefinitionSpec(
            node_type=PARSE_DATETIME_NODE_TYPE,
            node_version="1.0",
            display_name="Parse DateTime",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            input_table_slots=_single_transform_input_table_slots(),
            output_table_slots=_single_transform_output_table_slots(),
            config_schema=_parse_datetime_schema(),
        ),
        NodeDefinitionSpec(
            node_type=CONDITION_FLAG_NODE_TYPE,
            node_version="1.0",
            display_name="Condition Flag",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_condition_flag_schema(),
        ),
        NodeDefinitionSpec(
            node_type=JUMP_ANCHOR_NODE_TYPE,
            node_version="1.0",
            display_name="Jump Anchor",
            output_ports=(NodePortSpec("status"),),
            config_schema=_jump_anchor_schema(),
        ),
        NodeDefinitionSpec(
            node_type=UNCONDITIONAL_JUMP_NODE_TYPE,
            node_version="1.0",
            display_name="Unconditional Jump",
            input_ports=(NodePortSpec("in"),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_unconditional_jump_schema(),
        ),
        NodeDefinitionSpec(
            node_type=CONDITIONAL_JUMP_NODE_TYPE,
            node_version="1.0",
            display_name="Conditional Jump",
            input_ports=(NodePortSpec("condition", required=True),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_conditional_jump_schema(),
        ),
        NodeDefinitionSpec(
            node_type=LOOP_START_NODE_TYPE,
            node_version="1.0",
            display_name="Loop Start",
            input_ports=(NodePortSpec("in"),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_loop_start_schema(),
        ),
        NodeDefinitionSpec(
            node_type=LOOP_JUDGE_NODE_TYPE,
            node_version="1.0",
            display_name="Loop Judge",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_loop_judge_schema(),
        ),
        NodeDefinitionSpec(
            node_type=SUB_WORKFLOW_NODE_TYPE,
            node_version="1.0",
            display_name="Sub Workflow",
            input_ports=(NodePortSpec("in"),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_subworkflow_schema(),
        ),
        NodeDefinitionSpec(
            node_type=SAVE_MEMORY_TABLE_NODE_TYPE,
            node_version="1.0",
            display_name="Save Memory Table",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"), NodePortSpec("memory")),
            input_table_slots=(
                _input_table_slot(
                    "in",
                    display_name="Input table",
                    description="Table to pass through and save as memory output.",
                ),
            ),
            output_table_slots=(
                _current_output_table_slot(
                    "out",
                    display_name="Current table",
                    description="Original current table passed to the main chain.",
                ),
                _auxiliary_output_table_slot(
                    "memory",
                    display_name="Memory table",
                    description="Auxiliary memory table saved by the node.",
                    allow_new_memory=True,
                    allow_existing_memory=True,
                ),
            ),
            config_schema=_save_memory_table_schema(),
        ),
        NodeDefinitionSpec(
            node_type=SAVE_RUN_TABLE_NODE_TYPE,
            node_version="1.0",
            display_name="Save Run Table",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"), NodePortSpec("transit")),
            config_schema=_save_run_table_schema(),
        ),
        NodeDefinitionSpec(
            node_type=WRITE_SELECTED_COLUMNS_NODE_TYPE,
            node_version="1.0",
            display_name="Write Selected Columns",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_write_selected_columns_schema(),
        ),
        NodeDefinitionSpec(
            node_type=WRITE_BACK_TABLE_NODE_TYPE,
            node_version="1.0",
            display_name="Write Back Table",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_write_back_table_schema(),
        ),
        NodeDefinitionSpec(
            node_type=LIST_FILES_NODE_TYPE,
            node_version="1.0",
            display_name="List Files",
            output_ports=(NodePortSpec("out"),),
            output_table_slots=(
                _source_output_table_slot(
                    "out",
                    display_name="File list table",
                    description="Generated file metadata table.",
                ),
            ),
            config_schema=_list_files_schema(),
        ),
        NodeDefinitionSpec(
            node_type=BATCH_RENAME_FILES_NODE_TYPE,
            node_version="1.0",
            display_name="Batch Rename Files",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_batch_rename_files_schema(),
        ),
        NodeDefinitionSpec(
            node_type=PLUGIN_NODE_TYPE,
            node_version="1.0",
            display_name="Plugin Node",
            input_ports=(NodePortSpec("in"),),
            output_ports=(NodePortSpec("status"),),
            config_schema=_plugin_node_schema(),
        ),
        NodeDefinitionSpec(
            node_type=PUBLISH_SHARED_TABLES_NODE_TYPE,
            node_version="1.0",
            display_name="Publish Shared Tables",
            input_ports=(NodePortSpec("in", required=True),),
            output_ports=(NodePortSpec("out"),),
            config_schema=_publish_shared_tables_schema(),
        ),
        NodeDefinitionSpec(
            node_type=READ_SHARED_TABLES_NODE_TYPE,
            node_version="1.0",
            display_name="Read Shared Tables",
            output_ports=(NodePortSpec("out"),),
            config_schema=_read_shared_tables_schema(),
        ),
        NodeDefinitionSpec(
            node_type=SQL_MAPPING_NODE_TYPE,
            node_version="1.0",
            display_name="SQL Mapping",
            output_ports=(NodePortSpec("out"),),
            config_schema=_sql_mapping_schema(),
        ),
        NodeDefinitionSpec(
            node_type=DELAY_TEST_NODE_TYPE,
            node_version="1.0",
            display_name="Delay Test",
            output_ports=(NodePortSpec("out"),),
        ),
        NodeDefinitionSpec(
            node_type=FAULT_TEST_NODE_TYPE,
            node_version="1.0",
            display_name="Fault Test",
            output_ports=(NodePortSpec("out"),),
        ),
    )


def _input_table_slot(
    name: str,
    *,
    display_name: str,
    description: str,
    required: bool = True,
    allowed_storage_kinds: tuple[TableStorageKind, ...] = _READABLE_TABLE_STORAGE_KINDS,
) -> NodeTableInputSlotSpec:
    return NodeTableInputSlotSpec(
        name=name,
        display_name=display_name,
        description=description,
        required=required,
        allowed_storage_kinds=allowed_storage_kinds,
        default_source="upstream_current",
    )


def _single_transform_input_table_slots() -> tuple[NodeTableInputSlotSpec, ...]:
    return (
        _input_table_slot(
            "in",
            display_name="Input table",
            description="Workflow-local table to transform.",
            allowed_storage_kinds=_NODE_EXECUTION_READABLE_TABLE_STORAGE_KINDS,
        ),
    )


def _single_transform_output_table_slots() -> tuple[NodeTableOutputSlotSpec, ...]:
    return (
        NodeTableOutputSlotSpec(
            name="out",
            display_name="Result table",
            description="Primary transformed table for the workflow chain.",
            default_role=TableRole.CURRENT,
            allow_current=True,
            allow_new_memory=True,
            allow_new_runtime_sql=True,
            allow_existing_memory=True,
            allow_existing_runtime_sql=True,
        ),
    )


def _current_output_table_slot(
    name: str,
    *,
    display_name: str,
    description: str,
) -> NodeTableOutputSlotSpec:
    return NodeTableOutputSlotSpec(
        name=name,
        display_name=display_name,
        description=description,
        default_role=TableRole.CURRENT,
        allow_current=True,
    )


def _source_output_table_slot(
    name: str,
    *,
    display_name: str,
    description: str,
) -> NodeTableOutputSlotSpec:
    return NodeTableOutputSlotSpec(
        name=name,
        display_name=display_name,
        description=description,
        default_role=TableRole.CURRENT,
        allow_current=True,
        allow_new_memory=True,
        allow_new_runtime_sql=True,
        allow_existing_memory=True,
        allow_existing_runtime_sql=True,
    )


def _auxiliary_output_table_slot(
    name: str,
    *,
    display_name: str,
    description: str,
    allow_new_memory: bool = False,
    allow_new_runtime_sql: bool = False,
    allow_existing_memory: bool = False,
    allow_existing_runtime_sql: bool = False,
) -> NodeTableOutputSlotSpec:
    return NodeTableOutputSlotSpec(
        name=name,
        display_name=display_name,
        description=description,
        default_role=TableRole.AUXILIARY,
        allow_current=False,
        allow_new_memory=allow_new_memory,
        allow_new_runtime_sql=allow_new_runtime_sql,
        allow_existing_memory=allow_existing_memory,
        allow_existing_runtime_sql=allow_existing_runtime_sql,
    )


